add Linux check to m5 fire script

diff --git a/device_specific/flash_the_m5stack_fire b/device_specific/flash_the_m5stack_fire
--- a/device_specific/flash_the_m5stack_fire
+++ b/device_specific/flash_the_m5stack_fire
@@ -27,6 +27,11 @@ esp_idf_repo_url="https://github.com/espressif/esp-idf.git"
 chosen_device="M5Stack FIRE"
 tty_device="/dev/ttyACM0"
 
+if [ "$(uname -s)" != "Linux" ]; then
+  echo "ERROR: This script is only compatible with Linux." >&2
+  exit 1
+fi
+
 clear
 echo "------------------------------------------------------------"
 echo "------------------------------------------------------------"
